In [65]:
import numpy as np
import matplotlib.pyplot as plt

# Generate random 2D histogram data
num_histograms = 10
num_bins_x = 2
num_bins_y = 3

histograms = []
for _ in range(num_histograms):
    data = np.linspace(1, num_bins_x * num_bins_y, num_bins_x * num_bins_y)
    hist = data.reshape(num_bins_x, num_bins_y)
    histograms.append(hist)

histograms = np.array(histograms)

print(histograms.shape)
histograms.reshape(10, -1)
# num, (x, y)

(10, 2, 3)


array([[1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.]])

In [68]:
from numpy.testing import assert_allclose

def merge_bins(hist, min_occ=0.001):
    # normalize all 10 arrays

    normalized_hist = hist / np.sum(hist, axis=(1, 2), keepdims=True)
    print(normalized_hist.shape)
    print(normalized_hist)
    flattened_hist = normalized_hist.reshape(10, -1)
    print("Flattened Shape:", flattened_hist.shape)
    print(flattened_hist)
    combined_hist = np.sum(flattened_hist, axis=0)
    print("Combined Shape:", combined_hist.shape)
    print(combined_hist)
    hist_copy = hist.reshape(10, -1)
    print(hist_copy)

    
    assert_allclose(sum(combined_hist), len(hist), atol=1e-3)

    track_merges = [] # order of merges, sequentially
    merge_counter = 0

    # combined_hist = [0.5, 0.25, 1, 0.5, 1, 10, 1, 2, .06, 1]
    print("-----")
    print(combined_hist)
    # do we need to alter/delete? we just need to track the merges
    while np.min(combined_hist) < 1: #min_occ * len(hist):
        if len(combined_hist) == 1:
            break
        min_index = np.argmin(combined_hist)
        if min_index == 0:
            combined_hist[min_index] += combined_hist[min_index + 1]
            track_merges.append((min_index, min_index+1))
            combined_hist = np.delete(combined_hist, min_index + 1)
            merge_counter += 1
        elif min_index == len(combined_hist) - 1:
            combined_hist[min_index - 1] += combined_hist[min_index]
            track_merges.append((min_index-1, min_index))
            combined_hist = np.delete(combined_hist, min_index)
            merge_counter += 1
        else:
            if combined_hist[min_index - 1] < combined_hist[min_index + 1]:
                combined_hist[min_index - 1] += combined_hist[min_index]
                track_merges.append((min_index - 1, min_index))
                combined_hist = np.delete(combined_hist, min_index)
                merge_counter += 1
            else:
                combined_hist[min_index] += combined_hist[min_index + 1]
                track_merges.append((min_index, min_index+1))
                combined_hist = np.delete(combined_hist, min_index + 1)
                merge_counter += 1

    print(combined_hist)
    print('track_merges:', track_merges) 
    print(merge_counter)

    # hist = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    #                     [0.5, 0.2, 0.2, 5, 1, 1, 1, 2, .3, 1]])
                        


for i in range(len(merged_hist_copy)):
    for merge in track_merges:
        merged_hist_copy[i, merge[0]] += merged_hist_copy[i, merge[1]]

# Delete columns specified in track_merges
merged_hist_copy = np.delete(merged_hist_copy, [merge[1] for merge in track_merges], axis=1)
        # print(h)
    return hist_copy

#     return np.array(reduced_hists)

merge_bins(histograms)

(10, 2, 3)
[[[0.13043478 0.08695652 0.13043478]
  [0.17391304 0.2173913  0.26086957]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]]
Flattened Shape: (10, 6)
[[0.13043478 0.08695652 0.13043478 0.17391304 0.2173913  0.26086957]
 [0.04761905 0.0952381  0.14285714 0.19047619 0.23809524 0.28571429]
 [0.04761905 0.0952381  0.14285714 0.19047619 0.23809524 0.2857142

ValueError: cannot delete array elements

In [207]:
import numpy as np

def merge_array(input_arr, minOcc):
    """
    Merge array based on minOcc value. Return merged array (size=N) and merge_map.
    """
    pointer = 0
    add_pointer = 1
    merge_map = {}
    arr = input_arr.copy()

    while add_pointer < len(arr):

        # edge case: if first element is less than minOcc
        if pointer == 0 and arr[pointer] < minOcc:
            arr[0] += arr[add_pointer]
            merge_map[0] = merge_map.get(0, []) + [add_pointer]
            add_pointer += 1
            
        if arr[add_pointer] < minOcc:
            arr[pointer] += arr[add_pointer]
            merge_map[pointer] = merge_map.get(pointer, []) + [add_pointer]
            add_pointer += 1

        else:
            pointer = add_pointer
            add_pointer += 1

    merged_arr = np.delete(arr, [item for sublist in merge_map.values() for item in sublist], axis=0)
    
    return merged_arr, merge_map

## TESTING
# input_array = np.array([1., 2., 3., 4., 5., 6.])
input_array = np.array([6, 4., 1, 2, 6, 2, 3])
print("INPUT:", input_array_Merge)
target_value = 4
result_array, to_merge = merge_array(input_array, target_value) # PROBLEM: Mutateable array. should we be worried? Fixed via copy :11
print("OUTPUT", result_array)
print("TO merge:", to_merge)

print()

def merge_subArrays(subarr, merge_map):
    """
    Merge arrays (size=N) based on merge_map
    """
    arr = subarr.copy()

    for idx, merge_list in merge_map.items():    
        for merge_idx in merge_list:
            arr[idx] += arr[merge_idx]

    merged_arr = np.delete(arr, [item for sublist in merge_map.values() for item in sublist], axis=0)

    return merged_arr


#input_array = np.array([1., 2., 3., 4., 5., 6., 7]) # must be same size as input array for merge_array
# input_array = np.array([6, 4., 1, 2, 6, 2, 3])
print("INPUT:", input_array)
result_array = merge_subArrays(input_array, to_merge)
print("OUTPUT", result_array)



INPUT: [6. 4. 1. 2. 6. 2. 3.]
OUTPUT [ 6.  7. 11.]
TO merge: {1: [2, 3], 4: [5, 6]}

INPUT: [6. 4. 1. 2. 6. 2. 3.]
OUTPUT [ 6.  7. 11.]
