In [25]:
import numpy as np
import matplotlib.pyplot as plt

# Generate random 2D histogram data
num_histograms = 10
num_bins_x = 2
num_bins_y = 3

histograms = []
for _ in range(num_histograms):
    data = np.linspace(1, num_bins_x * num_bins_y, num_bins_x * num_bins_y)
    hist = data.reshape(num_bins_x, num_bins_y)
    histograms.append(hist)

histograms = np.array(histograms)

print(histograms.shape)
histograms
# num, (x, y)

(10, 2, 3)


array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [4., 5., 6.]]])

In [51]:
from numpy.testing import assert_allclose

def merge_bins(hist, min_occ=0.001):
    # normalize all 10 arrays

    normalized_hist = hist / np.sum(hist, axis=(1, 2), keepdims=True)
    print(normalized_hist.shape)
    print(normalized_hist)
    flattened_hist = normalized_hist.reshape(10, -1)
    print("Flattened Shape:", flattened_hist.shape)
    print(flattened_hist)
    combined_hist = np.sum(flattened_hist, axis=0)
    print("Combined Shape:", combined_hist.shape)
    print(combined_hist)
    assert_allclose(sum(combined_hist), len(hist), atol=1e-3)

    track_merges = [] # order of merges, sequentially
    merge_counter = 0

    combined_hist = [0.5, 0.25, 1, 0.5, 1, 10, 1, 2, .06, 1]
    print("-----")
    print(combined_hist)
    # do we need to alter/delete? we just need to track the merges
    while np.min(combined_hist) < 1: #min_occ * len(hist):
        min_index = np.argmin(combined_hist)
        if min_index == 0:
            combined_hist[min_index] += combined_hist[min_index + 1]
            track_merges.append((min_index, min_index+1))
            combined_hist = np.delete(combined_hist, min_index + 1)
            merge_counter += 1
        elif min_index == len(combined_hist) - 1:
            combined_hist[min_index - 1] += combined_hist[min_index]
            track_merges.append((min_index-1, min_index))
            combined_hist = np.delete(combined_hist, min_index)
            merge_counter += 1
        else:
            if combined_hist[min_index - 1] < combined_hist[min_index + 1]:
                combined_hist[min_index - 1] += combined_hist[min_index]
                track_merges.append((min_index - 1, min_index))
                combined_hist = np.delete(combined_hist, min_index)
                merge_counter += 1
            else:
                combined_hist[min_index] += combined_hist[min_index + 1]
                track_merges.append((min_index, min_index+1))
                combined_hist = np.delete(combined_hist, min_index + 1)
                merge_counter += 1

    print(combined_hist)
    print(track_merges) 
    print(merge_counter)


    merge_map = []
    new_index = 0

    # turn flattened hist using the same merge order
    for merge in track_merges:
        merge_map.append(merge[0])
        merge_map.append(merge[1])
        new_index += 1



#     return np.array(reduced_hists)

merge_bins(histograms)

(10, 2, 3)
[[[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]

 [[0.04761905 0.0952381  0.14285714]
  [0.19047619 0.23809524 0.28571429]]]
Flattened Shape: (10, 6)
[[0.04761905 0.0952381  0.14285714 0.19047619 0.23809524 0.28571429]
 [0.04761905 0.0952381  0.14285714 0.19047619 0.23809524 0.28571429]
 [0.04761905 0.0952381  0.14285714 0.19047619 0.23809524 0.2857142